---
title: "Safa's  Website"
description: |
  The following app created using RShiny for a data visualization course. The variables represented in this app are maximum price, city miles per gallon (MPG), highway MPG, and car size. The scatterplot is reactive to price and size inputs. Additional information about car sizes is also provided based on the user's selection.
output: distill::distill_article
---

<iframe src="https://safasiddiqui.shinyapps.io/WA06/" class="l-screen-inset shaded" height="800px"></iframe>

**Reflection: Briefly, reflect on the major decisions that you made in designing the
layout of the app and your logic/rationale for making that decision. Also discuss the alternative ideas and why you decided not to go with those.**

The first decision made as a group was which dataset to use. Some of the team members had used Cars in the past and found this dataset accessible and with interesting variables. After deciding on the dataset, we decided the target audience would be the general public with limited knowledge of cars. Once we had decided on the dataset and audience, we brainstormed the types of graphs/visualizations we wanted to include and went to the design board. We designed the layout to guide users naturally across the dashboard as they look from left-to-right and row-by-row (i.e. they first see the title at the top, then read left-to-right to make selections, then view the plot, etc.). The requirements of the assignment also drove some decision making for this part (e.g. a scatterplot that depicts bivariate analysis). We considered integrating more complex filters and variables, but decided against them to avoid overwhelming users inexperienced with cars. However, we decided on City MPG vs Highway MPG for the scatterplot as this would be useful to the common person who is making a decision about which car to buy. We also decided to filter the data by price and size of vehicle as those would be the second most important factors for most people when buying a car. We felt having the option to filter the scatterplot by both price and size of vehicle added more insight for the user. Finally, HTML tags were used to adjust the formatting of text to enhance the visual appeal of the dashboard. We originally planned to output an image or rows of the dataset based on the radio button input, but decided against this as it would not be as meaningful to users as an informative blurb about car sizes. We initially wanted a pale blue background for the app as shown in Figure 1, but ended up going with light purple because it looked better to us.

**Analysis: Briefly, explain the story that your app tells. What lessons or conclusions can you reach for your analysis using the app that you created. Make sure you provide evidence for all conclusions/claims that you make (this might include screenshots of visuals/outputs from the app if necessary).**

The Cars for Dummies app provides a simple summary of basic car attributes. Specifically, there is information on maximum price, highway MPG, city MPG, and size. The goal of the app is to illustrate how MPG changes with price and size. There is a scatterplot illustrating the relationship between highway MPG and city MPG, which changes with inputs of price and size. In general the scatterplot shows a positive correlation between highway MPG and city MPG. When looking at all size and prices, data points are more populated and close-together in the low MPG area. Overall, the scatterplot shows that higher-priced cars do not necessarily offer better fuel-efficiency, which may be of surprise to first-time car buyers. Many high priced cars have high city MPG, but moderate highway MPG. This filter also shows how few cars fall into the price range, regardless of size. By reading the detailed descriptions of car sizes, users can learn about the typical features and advantages of each size. This will likely inform their car-purchasing decisions. The selection of a car size also modifies the scatterplot. We can compare fuel efficiency by car size; both small and midsize cars have fuel efficiency that is comparable to all sizes–strong positive correlation and a higher concentration of vehicles in the low MPG region. Large vehicles appear to have a much weaker positive correlation between highway MPG and city MPG, and almost all of the large vehicles have very low city MPG.
  


